### ISSUE TITLE
Linter not working under WIndows 10

### ISSUE THREAD

**Issue by bmaschio** [fmontesi/linter-jolie#4]
@fmontesi 
I have tried to install Atom and the relative jolie packages 
but it seems to not work
![image](https://cloud.githubusercontent.com/assets/12083716/14834143/2428ca60-0c03-11e6-9ea4-979d01f5a8fc.png)

I think it is a problem with the location where jolie.bat is 

also if i run  as script from atom

![image](https://cloud.githubusercontent.com/assets/12083716/14834199/737b5b64-0c03-11e6-9b72-37a3c5e09870.png)

but I run jolie from cmd 

![image](https://cloud.githubusercontent.com/assets/12083716/14834240/a70e975c-0c03-11e6-86a5-9c3eed363f1e.png)

I am not sure what to think

**Comment by fmontesi** [comment]
Confirmed, I have the same issue on Windows 10.

It seems that we are not the only ones with this problem. It appears also with Python and PHP, and probably others. I see that in linter-php they decided to offer a configuration variable to allow users to fix it: https://atom.io/packages/linter-php

I haven't touched configuration yet, but it looks pretty easy to add judging from their code: https://github.com/AtomLinter/linter-php/blob/master/lib/main.coffee

I'm a bit short on spare time though.. maybe somebody at @mp2016/students has the same problem?

**Comment by bmaschio** [comment]
@fmontesi 

I have added  two console.log in coffee script 
line 18  console.log(editor.getPath())
line 20 console.log(data.stderr)

C:\Progetti\RilevazioneTimbrature\Leonardo\leonardo.ol
main.coffee:20 "jolie" non � riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

Sorry for the italian  it seems that it does not recognise the jolie command

**Comment by fmontesi** [comment]
I've added a new setting to point out the executable path explicitly. Try it out.

**Comment by bmaschio** [comment]
@fmontesi 

my Atom since to have not noticed the update to 0.70

![image](https://cloud.githubusercontent.com/assets/12083716/20435168/5cc8e07c-adab-11e6-8f75-48b203504632.png)

**Comment by fmontesi** [comment]
Weird, it should.. :-/

**Comment by bmaschio** [comment]
@fmontesi 
Have you got in mind the Donald Duck cartoons that is me with window today. but I arrived to a sort of conclusion the problem is not so much in path of jolie but how it is generated the command string to be passed to the cmd.
Atoms tryes to execute a command line that looks like 
"C:\Windows\System32\cmd.exe"
"/s"
"/d"
"/c"
""C:\Windows\System32\jolie.bat "--check" "C:\Progetti\PortaleManutenzioneAndroid\Leonardo\leonardo.ol"""

this is given by my atom version  (1.12.4) line 52
file:///C:/projects/atom/out/app/src/buffered-process.coffee

that adds some "" 

This is a know problem:
https://github.com/atom/atom/issues/3200
https://github.com/atom/atom/pull/3208

in theory should been solved

Lets see

**Comment by bmaschio** [comment]
@fmontesi 

Opened a new issue  on Atom Project https://github.com/atom/atom/issues/13295

**Comment by bmaschio** [comment]
@fmontesi 
They bounced me to this repository https://github.com/steelbrain/exec
I was pondering how the dependencies works in our linter

  "dependencies": {
    "atom-linter": "^3.1.0",
    "atom-package-deps": "^2.0.1"
  },  

how do I have to read ^3.1.0
If you go   https://github.com/steelbrain/linter that I think is the correct repository you find in package definition 

 "version": "1.11.4",

Are we pointing to the wrong version??' or am I getting something complacently wrong

tnk
B

**Comment by fmontesi** [comment]
The "dependencies" are deps on NPM packages, so not the linter atom package
you linked.

The dependencies from Atom packages are in "package-deps".

**Comment by bmaschio** [comment]
@fmontesi 
so  https://github.com/steelbrain/linter it is  NPM package  so i wander why we link at 3.10 when the version is 1.11.4

**Comment by bmaschio** [comment]
@fmontesi 
I opened a new issue on the npm sb-exec  https://github.com/steelbrain/exec/issues/59

**Comment by Arcanemagus** [comment]
I just installed this language, `language-jolie` and checked out `linter-jolie`. The program is being executed properly on Windows 10 x64 for me currently.

It looks like when this was filed this linter was still using an old version of the `atom-linter` helper library, which has since been corrected in v0.7.1. Are you still having issues on that version @bmaschio?

**Comment by fmontesi** [comment]
@arcanemagus Correct! I imagined bumping that version would help this issue, but I haven't tested it on Windows 10. Thanks for reporting that it works for you. @bmaschio Do you have the latest version of linter-jolie?

**Comment by fmontesi** [comment]
(it was @bmaschio himself to find out we were outdated)

**Comment by bmaschio** [comment]
@Arcanemagus  thanks for helping @fmontesi 
I am still having problem with windows 8.1 Pro

My  language-jolie   "version": "0.4.5"

My linter-jolie  "version": "0.7.1"  
my atom-linter version is 

        "raw": "atom-linter@^8.0.0",
        "scope": null,
        "escapedName": "atom-linter",
        "name": "atom-linter",
        "rawSpec": "^8.0.0",
        "spec": ">=8.0.0 <9.0.0",
        "type": "range"

am I getting something wrong

**Comment by Arcanemagus** [comment]
@bmaschio Can you completely remove the `linter-jolie` folder from The `C:\Users\username\.atom\packages` folder, then run `apm install linter-jolie` in order to get a fresh start? (Note that this won't wipe any settings.)

**Comment by bmaschio** [comment]
@Arcanemagus  No changes!! Is it possible something to do with Promise and window 8? when is  _child_process.spawn 

     spawnedProcess.on('close', function (exitCode) { it returns exitCode =1

**Comment by Arcanemagus** [comment]
@bmaschio What is the exact error you are getting now?

**Comment by bmaschio** [comment]
@Arcanemagus 

stderr = ""C:\Windows\system32\jolie.bat" non � riconosciuto come comando interno o esterno,
↵ un programma eseguibile o un file batch."

exactly as before..

**Comment by Arcanemagus** [comment]
And what do you get from `where.exe jolie`?

**Comment by bmaschio** [comment]
In C:\Windows\system32\

Am I missing something?

**Comment by Arcanemagus** [comment]
No, I mean what do you get when you run the command `where.exe jolie` on the CLI?

For example:
![image](https://cloud.githubusercontent.com/assets/427137/20722537/d5912a32-b61b-11e6-85e4-2f121b84ffa1.png)

**Comment by bmaschio** [comment]
@Arcanemagus 

![image](https://cloud.githubusercontent.com/assets/12083716/20722832/6400b228-b668-11e6-9e01-f943cfed5e16.png)

I have set now with even capital S 

![image](https://cloud.githubusercontent.com/assets/12083716/20722902/a7eef53a-b668-11e6-97f6-3e54a15ec291.png)

but the result is the same

![image](https://cloud.githubusercontent.com/assets/12083716/20722943/ceb87bfa-b668-11e6-9bf4-1d217fd5ae17.png)

thanks 

Balint

**Comment by Arcanemagus** [comment]
Can you run the following two commands?

```batch
C:\Windows\System32\cmd.exe /s /c "jolie "--version""
C:\Windows\System32\cmd.exe /s /c ""jolie" "--version""
```

I'm wondering if you are somehow hitting a variant of https://github.com/steelbrain/exec/issues/36.

**Comment by Arcanemagus** [comment]
Also, in Atom can you go File -> Config... and copy the contents related to `linter-jolie`

For example:
```cson
  "linter-jolie":
    jolieExecutablePath: "C:\\Jolie\\bin\\jolie.bat"
```

**Comment by bmaschio** [comment]
they both worked 

![image](https://cloud.githubusercontent.com/assets/12083716/20724015/012c74a2-b66d-11e6-88d9-3ced46d57dd8.png)


and

![image](https://cloud.githubusercontent.com/assets/12083716/20724211/9eaf1b4e-b66d-11e6-9d50-94229504f6e1.png)

**Comment by Arcanemagus** [comment]
That's what I'm seeing as well, which is the case for _most_ programs, but some are buggy...

Anyway can you post the config value?

**Comment by bmaschio** [comment]
![image](https://cloud.githubusercontent.com/assets/12083716/20724260/d5b9dc82-b66d-11e6-8052-97a8c7f42119.png)

**Comment by bmaschio** [comment]
@Arcanemagus maybe I am being cheeky have you got hangout?

**Comment by Arcanemagus** [comment]
Yep, I'm also on [Atom's Slack](https://discuss.atom.io/t/join-us-on-slack/16638).

**Comment by bmaschio** [comment]
would you find it easy on Hangout?

**Comment by bmaschio** [comment]
@Arcanemagus 

Ok the java linter it works fine on my pc

![image](https://cloud.githubusercontent.com/assets/12083716/20728570/9f5cbad6-b67e-11e6-8bf1-ca309548c494.png)


It must be something to do with jolie.bat

Talk soon

**Comment by Arcanemagus** [comment]
How bizarre 😕.
